### ISSUE TITLE
Migration to HTTPS zeroes Facebook page likes counters

### ISSUE THREAD

**Issue by hvelarde** [collective/sc.social.like#104]
Facebook differentiates URIs with different schema; technically that's correct, but in practice is a very stupid assumption that leads to the reset of all page likes counters on a site after the migration from HTTP to HTTPS.

this issue is very well documented since many years and Facebook has done nothing to solve or even mitigate it.

there are 2 known workarounds, according to the [developer's documentation](https://developers.facebook.com/docs/sharing/webmasters/crawler):

* exempt the Facebook crawler from the HTTPS redirect
* use the old page as the canonical URL for the new page

both of them could probably lead to lost of like counters of some other pages.

**Comment by hvelarde** [comment]
a third option could be getting statistics from the Facebook Graph API using both URI schemas, add the share counter and substitute that value in the widget.

that could "solve" the problem at the cost of 2 additional requests in approximately 0.5 seconds per page, per visitor:

* http://graph.facebook.com/http://www.cartacapital.com.br/sociedade/pau-grande-mas-subjugado-vai-ter-preto-humilhado-sim
http://graph.facebook.com/https://www.cartacapital.com.br/sociedade/pau-grande-mas-subjugado-vai-ter-preto-humilhado-sim

**Comment by hvelarde** [comment]
I was thinking we can keep it simpler if we implement the canonical URL; to avoid missing current counter we can add a date as a trigger.

for instance, let's say we started using HTTPS on January 10, 2017; we can add another field in the configlet to use this date to determine if we must use the old URL as canonical or not: all content published before that date will use old schema (HTTP) as canonical; all content published on that date (or after it) will use the current schema (HTTPS).

in the future this could turn into a behavior to solve other use cases like URL changes because of content moved or renamed.

@agnogueira comments?

**Comment by hvelarde** [comment]
we're going to solve this as described in #108.

**Comment by tcurvelo** [comment]
I know you chose another approach but, for the record, you don't need an additional request for getting data from both schemes. You can ask for multiple ids in the same request, using the `ids` arg. Eg.:

 -  http://graph.facebook.com/ids=http://www.cartacapital.com.br/sociedade/pau-grande-mas-subjugado-vai-ter-preto-humilhado-sim,https://www.cartacapital.com.br/sociedade/pau-grande-mas-subjugado-vai-ter-preto-humilhado-sim
```json
{
    "http://www.cartacapital.com.br/sociedade/pau-grande-mas-subjugado-vai-ter-preto-humilhado-sim": {
        "id": "http://www.cartacapital.com.br/sociedade/pau-grande-mas-subjugado-vai-ter-preto-humilhado-sim",
        "og_object": {
            "description": "Do estereótipo do \"bem dotado\" à marginalização, o Brasil mostra ser o país do escárnio e da violência",
            "id": "1508557802517973",
            "title": "Pau grande, mas subjugado: vai ter preto humilhado sim",
            "type": "article",
            "updated_time": "2017-07-08T20:23:26+0000"
        },
        "share": {
            "comment_count": 0,
            "share_count": 30496
        }
    },
    "https://www.cartacapital.com.br/sociedade/pau-grande-mas-subjugado-vai-ter-preto-humilhado-sim": {
        "id": "https://www.cartacapital.com.br/sociedade/pau-grande-mas-subjugado-vai-ter-preto-humilhado-sim",
        "og_object": {
            "description": "Do estereótipo do \"bem dotado\" à marginalização, o Brasil mostra ser o país do escárnio e da violência",
            "id": "1508557802517973",
            "title": "Pau grande, mas subjugado: vai ter preto humilhado sim",
            "type": "article",
            "updated_time": "2017-07-08T20:23:26+0000"
        },
        "share": {
            "comment_count": 0,
            "share_count": 255
        }
    }
}
```
