### ISSUE TITLE
Error when upgrading from 2.5 to latest 2.13b2

### ISSUE THREAD

**Issue by erral** [collective/sc.social.like#151]
When running the upgrade of sc.social.like from version 2.5 to latest 2.13b2 I get the following error (Plone 4.3.15): 

```
2017-11-29 11:27:34 ERROR Zope.SiteErrorLog 1511951254.260.652666381467 http://egoibarra.cs/portal_setup/manage_doUpgrades
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.GenericSetup.tool, line 1053, in manage_doUpgrades
  Module Products.GenericSetup.upgrade, line 166, in doStep
  Module sc.social.like.upgrades.v3041, line 9, in register_cover_tiles
  Module plone.api.portal, line 2, in get_registry_record
  Module plone.api.validation, line 77, in wrapped
  Module plone.api.portal, line 340, in get_registry_record
InvalidParameterError: Cannot find a record with name 'plone.app.tiles'
```
The 3041 profile upgrade tries to install the tiles for collective.cover, but if there is neither cover nor plone.app.tiles installed the upgrade step fails.

[If I just add a try except in the upgrade](https://github.com/collective/sc.social.like/commit/b5548bab0720373bc84b84df7dbadf2b672e1d64) the upgrade step is run correctly.

What do you think?

**Comment by hvelarde** [comment]
I left a message in the commit.
