### ISSUE TITLE
Should we add more social networks as default installation?

### ISSUE THREAD

**Issue by idgserpro** [collective/sc.social.like#168]
We have Twitter and Facebook as default networks for this package.

https://github.com/collective/sc.social.like/blob/54d7a5f798d992bd6eba5f5e45cf09d4ace28500/sc/social/like/profiles/default/registry.xml#L11,L12

Linkedin and Whatsapp have come a long way since this package was created. We suggest if they shouldn't be added as default as well.

**Comment by hvelarde** [comment]
you can do that as part of your own policy.
