### ISSUE TITLE
Why is whatsapp with "display:none" in this package?

### ISSUE THREAD

**Issue by idgserpro** [collective/sc.social.like#169]
https://github.com/collective/sc.social.like/blob/2ae338c32803d57e2298a0cb1715da5c9266a6f8/sc/social/like/browser/stylesheets/social_like.css#L68

**Comment by hvelarde** [comment]
I think this is because we need to find out via JS if we're running on a mobile device.

maybe @rodfersou remembers.

**Comment by rodfersou** [comment]
exactaly: 
https://github.com/collective/sc.social.like/blob/22763d659c333285c6fd9c893afe6c5d70201407/sc/social/like/browser/scripts/social_like.js#L15-L17
https://github.com/collective/sc.social.like/blob/2ae338c32803d57e2298a0cb1715da5c9266a6f8/sc/social/like/browser/stylesheets/social_like.css#L80-L83
