### ISSUE TITLE
Make new release to pypi

### ISSUE THREAD

**Issue by pgrunewald** [collective/sc.social.like#171]
Hi,
it would be great to have a new release on pypi to have the latest bug fixes.

**Comment by hvelarde** [comment]
there is an issue (Title level inconsistent) on the package documentation that must be fixed first:

https://travis-ci.org/collective/sc.social.like/jobs/630044869#L1770

CC @idgserpro

**Comment by idgserpro** [comment]
@hvelarde I made a PR. Can you merge and create a release please?

**Comment by idgserpro** [comment]
Release created in https://github.com/collective/sc.social.like/releases/tag/2.13.
