### ISSUE TITLE
Remove view social_likes_view

### ISSUE THREAD

**Issue by idgserpro** [collective/sc.social.like#176]
What is the [social_likes_view](https://github.com/collective/sc.social.like/blob/2e67159bc1e6c9008cf38b5ba2e6b53d4dec646f/sc/social/like/browser/configure.zcml#L11-L18) view for? It's not used anywhere in package. Is it any integration? It looks like old code that was in the package.

@hvelarde @ericof ?

**Comment by cleberjsantos** [comment]
@idgserpro Yes, that's old code that was exchanged for https://github.com/collective/sc.social.like/blob/2e67159bc1e6c9008cf38b5ba2e6b53d4dec646f/sc/social/like/browser/configure.zcml#L29-L35

@ericof @hvelarde Am I right?

**Comment by hvelarde** [comment]
I have no idea.
