### ISSUE TITLE
Facebook action not shown

### ISSUE THREAD

**Issue by hvelarde** [collective/sc.social.like#24]
Brand new installation with default configuration, Facebook action not shown even as selected:

![imagem da pgina 2014-01-05 - 16 33 08](https://f.cloud.github.com/assets/341393/1933524/e5345f46-7edc-11e3-9ae5-04d9fb42cc42.png)
![imagem da pgina 2014-01-05 - 16 32 53](https://f.cloud.github.com/assets/341393/1933523/e53413f6-7edc-11e3-84b9-31946d3bd10d.png)

**Comment by keul** [comment]
Safe for me: all is ok.

Remember also that old version of the Facebook widget was not displayed using "localhost".
