### ISSUE TITLE
Button style is always vertical

### ISSUE THREAD

**Issue by hvelarde** [collective/sc.social.like#25]
Brand new installation with default configuration, action buttons are always shown in vertical mode:

![imagem da pgina 2014-01-05 - 16 33 08](https://f.cloud.github.com/assets/341393/1933546/47c026cc-7edd-11e3-800e-e970e9d620af.png)
![imagem da pgina 2014-01-05 - 16 32 53](https://f.cloud.github.com/assets/341393/1933547/47c18a12-7edd-11e3-91f5-602796359e0c.png)

**Comment by keul** [comment]
I did some tests on new installation of master in the week-end for other issues but I didn't get that issue:

https://raw.githubusercontent.com/collective/sc.social.like/facebook-share/docs/screenshot1.png

https://raw.githubusercontent.com/collective/sc.social.like/facebook-share/docs/screenshot2.png

Maybe somebody already fixed it?
