### ISSUE TITLE
Facebook plugin "fix_iso" method in utils.py: two-letter language codes not handled well

### ISSUE THREAD

**Issue by rbruch** [collective/sc.social.like#29]
For example, in a site with default_language of "en", fix_iso returns "en_GB", given the list of Facebook locales as it currently exists (April 2014).

Not sure what the right answer is. Is there some other place in a Plone site where we could get a hint as to the correct locale? Or is there a commonly-accepted "default" mapping of the two-letter codes to the more-specific codes?

**Comment by hvelarde** [comment]
could you please take a look at this now? many changes have been made to the package in the last months.

**Comment by hvelarde** [comment]
closing as I got no feeedbak
