### ISSUE TITLE
Facebook plugin: "data-send" attribute not used anymore?

### ISSUE THREAD

**Issue by rbruch** [collective/sc.social.like#30]
I can't find "data-send" in the Facebook Like button documentation as of April 2014.
https://developers.facebook.com/docs/plugins/like-button/
The Facebook plugin "plugin.pt" template includes the attribute as "data-send=false". If it's true that the attribute is no longer used, it can be deleted from the plugin.

**Comment by hvelarde** [comment]
could you please take a look at this now? many changes have been made to the package in the last months.

**Comment by hvelarde** [comment]
closing as I got no feeedbak
