### ISSUE TITLE
Load social media JavaScript only when buttons are used

### ISSUE THREAD

**Issue by keul** [collective/sc.social.like#36]
During the developing of https://github.com/collective/sc.social.like/pull/35 I found that social JavaScript sources are always loaded, even if the page will not load social buttons.

For example: if you go in edit of a document social buttons will not be displayed but the page will be filled by all social plugins scripts. Is this a wanted behavior or something we can fix?

**Comment by hvelarde** [comment]
I think this is something we definitely want to fix; isn't it @agnogueira @ericof?

**Comment by keul** [comment]
Let me know, I will work on this in that case

**Comment by hvelarde** [comment]
please, do it; thanks!
