### ISSUE TITLE
Facebook's like action style issue

### ISSUE THREAD

**Issue by keul** [collective/sc.social.like#38]
Recently we noted that clicking on Facebook like action is opening a sort of overlay (not a popup) that current styles are forcing to be really small.

![schermata 2015-02-20 a 09 24 38](https://cloud.githubusercontent.com/assets/284924/6283300/cb5887dc-b8e2-11e4-897d-fda8d5ad25c3.png)

The issue is related to `iframe` which is forced to be 23px in height.
The style has been added lot of years ago (https://github.com/collective/sc.social.like/commit/ab07c98e572558b5b494a0bc9e274d9e3baf02d0#diff-d195fc97c1e1fa75baa93a1e5d22519eR5) so I think that something's changed in Facebook generated HTML.

After removing the style I get this:

![schermata 2015-02-20 a 09 32 21](https://cloud.githubusercontent.com/assets/284924/6283344/6fc626c6-b8e3-11e4-9bd3-0f83fb04eac5.png)

Can we safely remove it of there are other related style issues?

**Comment by cleberjsantos** [comment]
:+1: Does not there are other related style issues, then, we can safely remove ;) @agnogueira ?

**Comment by keul** [comment]
Let me know, I can take perform the change and some browser tests

**Comment by agnogueira** [comment]
I think its related to old facebook button. +1 to remove

**Comment by hvelarde** [comment]
@keul I think an upgrade step for cooking the CSS registry was needed here; I already make a release but if you add it, I will release it again.

**Comment by keul** [comment]
OK, I can fix this tomorrow

**Comment by keul** [comment]
@hvelarde done, just do not release another version. I'm going to take over PR #15 and finally close all needed feature we have on sc.social.like

**Comment by hvelarde** [comment]
thanks you, very much!
