### ISSUE TITLE
Add Whatsapp buttom

### ISSUE THREAD

**Issue by agnogueira** [collective/sc.social.like#39]
We need to add a whatsapp button to social.like.
A lot of websites is using, with better results than twitter and g+ in mobile

**Comment by hvelarde** [comment]
seems to be very easy to accomplish using the [custom URL scheme](http://stackoverflow.com/a/28618547):

    <a href="whatsapp://send?text=Hello%20World!">Share</a>

**Comment by rodfersou** [comment]
@agnogueira is this plugin supposed to work at normal desktop browser? or is it better to make it show up just at mobile devices? (we can detect with user agent it it is a mobile device)
