### ISSUE TITLE
The FB sharer

### ISSUE THREAD

**Issue by dtordable** [collective/sc.social.like#41]
I'm trying to use sc.social.like as a social sharer but found somewhat an error with the FB sharer.

Doesn't appear in the sharers box and FB seems not to exist along with the other sharers. I see +1, Linked in, Pinterest and twitter (and only tried twitter one that worked) but about Facebook doesn't appear at all.

It is a good product, but needs a bit of hack to make it work.
Thank you very much for this product.

- Daniel Tordable Dasilva

**Comment by keul** [comment]
Are you trying it on a local machine? Facebook will not work on "localhost:8080".

I'm using the last 2.1 version in production and all is ok
Example [here](http://www.ospfe.it/area-comunicazione/news/perfezionamento-in-musica-e-musicoterapia-in-neurologia/musica-e-musicoterapia-in-neurologia)

**Comment by dtordable** [comment]
It is on a server, to be honest, the machine at http://www.danieltordable.net/

**Comment by keul** [comment]
Looking at your HTML, the Facebook section is empty:

    <div class="sociallike-network-facebook">
    
    </div>

Are you sure you activated at least one of the plugins inside the Facebook configuration subpanel?

**Comment by dtordable** [comment]
Do I need another product installed on Plone?

**Comment by dtordable** [comment]
ahhh, it's on the facebook configuration, let me check it.

**Comment by keul** [comment]
@dtordable no... just go in the sc.social.like settings (https://raw.githubusercontent.com/collective/sc.social.like/master/docs/control_panel.png), then in the Facebook subpanel (link "Facebook" on the bottom).

**Comment by dtordable** [comment]
Do I need the Facebook APP ID to make it work?
