### ISSUE TITLE
Pinterest plugin with vertical style is not supported

### ISSUE THREAD

**Issue by keul** [collective/sc.social.like#42]
During my recent development I didn't find a way to provide a "large" vertical layout version of Pinterest plugin.
Recently I discovered that this kind of layout exists also for Pinterest.
![schermata 2015-03-31 a 17 30 01](https://cloud.githubusercontent.com/assets/284924/6922843/5f1be770-d7ce-11e4-960e-e224789feac0.png)

Example here: http://www.repubblica.it/economia/2015/03/31/news/inflazione_ferma_a_marzo_prezzi_in_calo_dello_0_1_-110887967

How to provide it? Where this is documented?

**Comment by hvelarde** [comment]
maybe you can find it over here: https://developers.pinterest.com/pin_it/

**Comment by keul** [comment]
@hvelarde probably, but last time I checked I didn't found anything about this.
To be checked!

**Comment by keul** [comment]
I'm not interested in this anymore, but still: https://github.com/pinterest/widgets/issues/55#issuecomment-187412523

**Comment by hvelarde** [comment]
I'm closing this one, then; if anybody shows interest in the future we can refer to this.
