### ISSUE TITLE
 Connection issue for pluggins: facebook, g + and twitter

### ISSUE THREAD

**Issue by yulmiro** [collective/sc.social.like#45]
I'm having a connection issue for pluggins: facebook, g + and twitter, when sharing on Facebook, it doesn't show the count and doesn't display the contents on the Facebook page, the g + displays a precaution icon and doesn't indicate any connection to google, in the case of twitter, it tweets the content but doesn't display the count in the pluggin.

**Comment by hvelarde** [comment]
I think your problem has nothing to do with this package.
