### ISSUE TITLE
A warning icon with Google +

### ISSUE THREAD

**Issue by macagua** [collective/sc.social.like#47]
Hi @hvelarde 

I have a problem when I trying to share a Plone page into Google+, because when I click the Google+ icon, show me a warning icon like this:

![googleplus_plone](https://cloud.githubusercontent.com/assets/185395/7717186/b52bc108-fe66-11e4-974c-0acd89fcb24e.png)

I am using the following buildout configuration with Python 2.7 and Debian 7:

```
[buildout]
extends =
    http://dist.plone.org/release/4.3.3/versions.cfg

find-links =
    http://dist.plone.org/release/4.3.3/
    http://dist.plone.org/thirdparty/

newest = false
show-picked-versions = true
eggs =
    sc.social.like
zcml =
versions = versions

parts = instance
    lxml

[versions]
sc.social.like = 2.2
plone.dexterity = 2.2.0

[instance]
recipe = plone.recipe.zope2instance
user = admin:admin
http-address = 8080
eggs =
    Plone
    plone.app.upgrade
    ${buildout:eggs}
zcml = ${buildout:zcml}
enviroment-vars =
    zope_i18n_compile_mo_files true

[lxml]
recipe = z3c.recipe.staticlxml
egg = lxml
parts =
```

Any idea?

**Comment by hvelarde** [comment]
no idea; check the JS console in search for some other messages

**Comment by yulmiro** [comment]
@macagua @hvelarde   I have the same problem in a the clean Plone configuration

![imageg](https://cloud.githubusercontent.com/assets/7870830/7730695/8363353c-fee5-11e4-861e-d7bdb6e39852.png)

I am using the following buildout configuration:

[buildout]
parts = 
    instance
    zopepy
    i18ndude
    zopeskel
    test

extends =
    http://dist.plone.org/release/4.3.3/versions.cfg

find-links =
    http://dist.plone.org/release/4.3.3
    http://dist.plone.org/thirdparty

extensions =
    mr.developer
#    buildout.dumppickedversions

sources = sources

versions = versions

develop =

[instance]
recipe = plone.recipe.zope2instance
user = admin:admin
http-address = 8080
debug-mode = off
verbose-security = on
blob-storage = var/blobstorage

eggs =
    PIL
    Plone
    sc.social.like   
 
zcml =

[zopepy]
recipe = zc.recipe.egg
eggs = ${instance:eggs}
interpreter = zopepy

[i18ndude]
unzip = true
recipe = zc.recipe.egg
eggs = i18ndude

[test]
recipe = zc.recipe.testrunner
defaults = ['--auto-color', '--auto-progress']
eggs =
    ${instance:eggs}

[zopeskel]
recipe = zc.recipe.egg
eggs =
    ZopeSkel
    PasteScript
    zopeskel.dexterity

[sources]

[versions]

ZopeSkel = 2.21.2
sc.social.like = 2.2
plone.dexterity = 2.2.0

**Comment by macagua** [comment]
Checking the JS console said:

```
Uncaught TypeError: undefined is not a function confirmed?hl=es-419&url=http://localhost:8080/Plone/front-page&t=1432133911157&source=w…:496(anonymous function) confirmed?hl=es-419&url=http://localhost:8080/Plone/front-page&t=1432133911157&source=w…:496
```

Then I click on the error and the reference to:

```
<script>window['__initBubble']();</script>
```

I searched the Internet and displays this entry:

http://stackoverflow.com/questions/20431552/uncaught-typeerror-object-object-global-has-no-method-initbubble

**Comment by keul** [comment]
Not sure if it's related. The `data-href` attribute is taken from view.url, so it should be ok.
https://github.com/collective/sc.social.like/blob/a247305129e6a564e0e3e5b3cfc493252aed7327/sc/social/like/plugins/gplus/browser.py#L29

**Comment by hvelarde** [comment]
@macagua is this still valid?
