### ISSUE TITLE
Add a skin machinary

### ISSUE THREAD

**Issue by rodfersou** [collective/sc.social.like#48]
Some sites requires that the default icon of social media networks be changed to match the layout of the site, and don't look as an alien into the site.

![icons](https://cloud.githubusercontent.com/assets/341393/7816685/2d564d8a-03a6-11e5-9379-2dbb7d8df81b.png)

So with this issue we need to do:

1. Study how in practice we can change the icons of all networks, there are some references for it:
  1. Maybe we can try to make the customization making the entire social network transparent with css opacity: 0 and put it in front of the desired icon.
  2. [Ridiculously Responsive Social Sharing Buttons](https://github.com/kni-labs/rrssb) looks like it resolves the problem about change icons.
  3. [Add this](http://www.addthis.com/) add another widget, so it is probably not a good choice.
  4. [Facebook has an option to change the buttom](https://developers.facebook.com/docs/plugins/share-button)
  5. [Twitter don't allow it](https://dev.twitter.com/web/tweet-button)
  6. Other idea is to use a [bare link](http://petragregorova.com/articles/social-share-buttons-with-custom-icons/) with cost of keep updating the links if platform changes.
2. Add a folder structure with some css and resources with the rules to change the icons.
3. Add a registration in sc.social.like configuration panel to have a combo box to switch to the desired icons (maybe with some preview)

**Comment by rodfersou** [comment]
@hvelarde @agnogueira I did a prove of concept about the idea to make the network transparent here: https://github.com/collective/sc.social.like/pull/49

Please take a look

**Comment by rodfersou** [comment]
Question, what is the better way to add the icons?
*  sprite images
*  [font icons](http://fortawesome.github.io/Font-Awesome/get-started/)
*  [svg sprites](https://css-tricks.com/svg-sprites-use-better-icon-fonts/)

**Comment by rodfersou** [comment]
@djowett @agnogueira @felipeduardo could you please share ideas about it?

**Comment by djowett** [comment]
Not in view for me at the moment, but /gets on soapbox/ I will say that I don't like the tracking of users by social networks or by button providers like addthis, merely by use of their provided buttons (whether or not people click).  
/gets off soapbox/
If you use the [bare link](http://petragregorova.com/articles/social-share-buttons-with-custom-icons/) you suggested, then the only machinery you need is the portal_actions & a bunch of svg images. You won't get all the likecount / sharecount / ... on the buttons though....

**Comment by rodfersou** [comment]
@djowett thank you, the problem with bare link we saw is that the chances the provider change the URL and we need to do a new release are higher than if we leave this responsibility to the provider to update how the link should be done.

Did you see my prove of concept at pull #49 ? With this trick I can change the icons just with CSS without changing the way sc.social.like works now.

But I see with good eyes your concern about tracking (I don't like it either) maybe we can think about to have both options in the configuration of sc.social.like in the future :)

**Comment by djowett** [comment]
@rodfersou portal_actions are editable through the ZMI without a new release, this is an example from a project where I've done this...  Note the parameters for the URL & title....

      <object name="stumbleupon" meta_type="CMF Action"
         i18n:domain="project.name">
       <property name="title" i18n:translate="">StumbleUpon</property>
       <property name="description"
          i18n:translate="">Post this story to StumbleUpon</property>
       <property
          name="url_expr">string:http://www.stumbleupon.com/submit?url=${object/absolute_url}&amp;title=${object/Title}</property>
       <property name="link_target">share_project</property>
       <property
          name="icon_expr">string:${portal_url}/++resource++project.name.images/socialmedia_stumbleupon.png</property>
       <property name="available_expr"></property>
       <property name="permissions"/>
       <property name="visible">True</property>
      </object>

**Comment by hvelarde** [comment]
@djowett ``portal_actions`` don't solve our use case because we need to maintain the same functionality that we have right now, that is opening a small new window on the action to allow the user to log into the networks and/or review the post..

@keul what do you think? do you have similar requirements on your projects?

**Comment by djowett** [comment]
@hvelarde yes, sure... you won't be able to do everything (click counts etc) with just portal_actions, though you can set a target window, but you can't size it (unless you use JQuery magic).   
Anyway don't worry - just a passing suggestion.

**Comment by fulv** [comment]
Just my 1c:  some JQuery magic is already being used with links provided by
portal_actions, e.g. the overlay for login, register, etc:

https://github.com/plone/Products.CMFPlone/blob/4.3.5/Products/CMFPlone/skins/plone_ecmascript/popupforms.js#L76

**Comment by rodfersou** [comment]
@djowett right now I'm not focusing with click counts, just to skin using one image, and I could make it works just with CSS here #49
