### ISSUE TITLE
sc.social.like and the Cookie Law

### ISSUE THREAD

**Issue by keul** [collective/sc.social.like#51]
Don't know if everybody knows about the recent european **Cookie Law**.
In two words (I'm not an expert and there's a lot of doubts about how to interpreter it): a lot of european site's, not only public companies, started to provide a "cookie displaimer" message about how cookies are used by the site itself. This became extremely awkward when cookies cames from social networks.

----

A big customers of us want to keep social buttons but asked for a (big) change in sc.social.like: a new configuration button that disable cookie scripts and only render links for sharing contents while `meta` tags for better sharing infos will remain the same.

Some examples:
* https://developers.facebook.com/docs/sharing/reference/share-dialog
* https://dev.twitter.com/web/tweet-button/web-intent
* https://developer.linkedin.com/docs/share-on-linkedin
* https://developers.google.com/+/web/share/?hl=it#sharelink

We must work on this. Will this pull request be something that can be evaluated in the product's core?

**Comment by hvelarde** [comment]
@yes, of course; I don't see any issues with it.

@agnogueira @rodfersou ?

**Comment by rodfersou** [comment]
I don't see any problem. It will be easier to make the social like theme this way too
