### ISSUE TITLE
add Telegram sharing

### ISSUE THREAD

**Issue by NightWorx** [collective/sc.social.like#52]
Along with the "Share with WhatsApp" Button for mobile, it would be nice to have a "Share with Telegram" Button (mind the desktop app)

(see also here https://github.com/DrKLO/Telegram/issues/652)

**Comment by hvelarde** [comment]
one issue per feature, please.

**Comment by NightWorx** [comment]
updated

**Comment by hvelarde** [comment]
are you still interested on this?
