### ISSUE TITLE
Use canoniacl object in case of context being default view of its parent

### ISSUE THREAD

**Issue by Martronic-SA** [collective/sc.social.like#59]
In the case where context is the default view of its parent, use the canonical object for the title and link to share.

in plugins views use :
    def __init__(self .......):
        self.url = self.context_state.canonical_object_url()
        self.title = self.context_state.canonical_object().title

the same in share links methods
        params = dict(
            text=self.title,
            url=self.url,
        )

be careful with the encoding of the title when using urlencode(params)

**Comment by hvelarde** [comment]
feel free to open a new branch with the proposed changes and create a PR.

**Comment by hvelarde** [comment]
closing as no further feedback was received and we have no such use case.
