### ISSUE TITLE
sc.social like upgrade fails on adding facebook button 'Like'

### ISSUE THREAD

**Issue by fredvd** [collective/sc.social.like#60]
Related to #1 to use plone.app.registry.

There's an issue with upgrading from previous versions of sc.social.like that has come up twice now in installed base for me: v3010 updates propertiestools.xml that tries to add an already existing option 'Like' to the fbbuttons lines property which trows a traceback deep down in OFS.Propertymanager:

` Module Products.GenericSetup.tool, line 914, in manage_doUpgrades
  Module Products.GenericSetup.upgrade, line 140, in doStep
  Module sc.social.like.upgrades.v3010.handler, line 20, in apply_profile
  Module plone.app.upgrade.utils, line 112, in loadMigrationProfile
  Module Products.GenericSetup.tool, line 353, in runAllImportStepsFromProfile
   - __traceback_info__: profile-sc.social.like.upgrades.v3010:default
  Module Products.GenericSetup.tool, line 1123, in _runImportStepsFromContext
  Module Products.GenericSetup.tool, line 1036, in _doRunImportStep
   - __traceback_info__: propertiestool
  Module Products.CMFPlone.exportimport.propertiestool, line 36, in importPloneProperties
  Module Products.GenericSetup.utils, line 507, in _importBody
  Module Products.CMFPlone.exportimport.propertiestool, line 104, in _importNode
  Module Products.CMFPlone.exportimport.propertiestool, line 147, in _initObjects
  Module Products.CMFPlone.exportimport.propertiestool, line 77, in _importNode
  Module Products.GenericSetup.utils, line 724, in _initProperties
  Module OFS.PropertyManager, line 184, in _setProperty
BadRequest: Invalid or duplicate property id`

I guess what happens is that when starting the site and going to the SL control panel the schema's default value u('Like',) is already writing this to the propertysheet with a ProxyFieldProperty (from Products.CMFDefault.formlib.schema import ProxyFieldProperty) before the GS profile is applied and then tries to do this again.

Would is be enough to enable purge='True' on the lines property in v3010 propertiestool.xml to at least prevent others from researching this again while upgrading older installations, even after we move to p.a.registry this is still in there and there's little chance that people have added more button styles in older sc.social.like versions anyway.

**Comment by hvelarde** [comment]
I have already noticed that but I though it was my mistake and closed the issue (#46).
