### ISSUE TITLE
Does not appear to work in Plone 5

### ISSUE THREAD

**Issue by rileydog** [collective/sc.social.like#63]
Installed as directed.
during buildout, got version 2.4.  No errors noted.
after restart, site would not open - 502 error
removed product and site works fine
Can I provide more information to help this issue?

**Comment by hvelarde** [comment]
seems that Plone 5.0 is listed as supported by mistake. @agitator is working on it on this branch, but I don know the status: https://github.com/collective/sc.social.like/tree/plone5

**Comment by hvelarde** [comment]
I released [2.4.1](https://pypi.python.org/pypi/sc.social.like/2.4.1) which fixes the inconsistence; package is not Plone 5 compatible yet.
