### ISSUE TITLE
Hide social like for unpublished content

### ISSUE THREAD

**Issue by rodfersou** [collective/sc.social.like#83]
One of our customer complain that facebook has a high share number for unpublished content:

![highshare](https://cloud.githubusercontent.com/assets/131209/19556917/28f390b4-96a2-11e6-86c8-e5ff8633edee.png)

It looks like facebook has a bug that it treat every unpublished post as the same post, and counts on.

To hide false positives we should hide social like for unpublished content.

**Comment by lepri** [comment]
This is not a good correction for this issue. If the portal has another state than published for publish  its contents, or another workflow, the viewlet will show up.

**Comment by hvelarde** [comment]
@lepri thanks for your comments; do you have a different use case? please elaborate on a new issues and feel free to propose a solution for that in another PR.
