### ISSUE TITLE
Social like just add image metadata for Archetypes content type

### ISSUE THREAD

**Issue by rodfersou** [collective/sc.social.like#87]
Social likes check if context provides `Products.Archetypes.interfaces.IBaseContent` when [try to get image object](https://github.com/collective/sc.social.like/blob/master/sc/social/like/utils.py#L19) and it ends with image not loaded at metadata:

```html
  <meta property="og:image" content="http://www.conversaafiada.com.br/logo.png" />
```

if you try [facebook sharing debugger](https://developers.facebook.com/tools/debug/sharing/?q=http%3A%2F%2Fwww.conversaafiada.com.br%2Feconomia%2Fo-que-une-parente-a-fhc-alem-da-petrobrax) it says that image is too small:

```
Image Too Small
Provided og:image URL, http://www.conversaafiada.com.br/logo.png was not valid because it did not meet the minimum size constraint of 200px by 200px.
```

**Comment by rodfersou** [comment]
@ericof you wrote this code, why do we need this check? any advise on how to fix it?

**Comment by ericof** [comment]
@rodfersou og:image has a min size for images, and it seems the logo image provided is smaller than that.
About the old code, no idea.

**Comment by rodfersou** [comment]
@ericof thank you for you help

**Comment by rodfersou** [comment]
digging deeper into the code, the problem was not that part of the cache, but the problem happen in [this line](https://github.com/collective/sc.social.like/blob/master/sc/social/like/utils.py#L47) when try to scale the image.

**Comment by rodfersou** [comment]
Closing this issue and pull request, it will be explained and fixed in other package
