### ISSUE TITLE
Add Share by email action

### ISSUE THREAD

**Issue by hvelarde** [collective/sc.social.like#91]
We need to make visible the `@@send_to` view available on Plone:

https://www.conversaafiada.com.br/brasil/golpe-foi-para-abafar-a-lava-jato/sendto_form

**Comment by rodfersou** [comment]
by "make visible" you mean create an icon that open a overlay with this form inside?

**Comment by hvelarde** [comment]
yes, and it should work in both: Plone 4 and Plone 5; ask @agnogueira for an icon.

**Comment by rodfersou** [comment]
@agnogueira pointed to use this icon https://commons.wikimedia.org/wiki/Category:E-mail_icons#/media/File:Aiga_mail.svg

**Comment by rodfersou** [comment]
Houston, we have a problem:
```
Erro
Não é permitido enviar esse link.
```

When I try to use the form

**Comment by rodfersou** [comment]
we changed to this icon http://fontawesome.io/icon/envelope/ https://commons.wikimedia.org/wiki/File:Envelope_alt_font_awesome.svg?uselang=pt-br
